

setGeneric(name="get_N", 
					 def=function(.Object) standardGeneric("get_N"), 
					 valueClass = "numeric")
setGeneric(name="get_K", 
					 def=function(.Object) standardGeneric("get_K"), 
					 valueClass = "numeric")
setGeneric(name="get_recaptures", 
					 def=function(.Object, id) standardGeneric("get_recaptures"),
					 valueClass = "numeric")
setGeneric(name="get_recaptures_matrix",
					 def=function(.Object) standardGeneric("get_recaptures_matrix"),
					 valueClass = "matrix")
setGeneric(name="get_surveys",
					 def=function(.Object) standardGeneric("get_surveys"),
					 valueClass = "numeric")
setGeneric(name="get_births",
					 def=function(.Object) standardGeneric("get_births"),
					 valueClass = "numeric")
setGeneric(name="get_first_obs",
					 def=function(.Object) standardGeneric("get_first_obs"),
					 valueClass = "numeric")
setGeneric(name="get_last_obs",
					 def=function(.Object) standardGeneric("get_last_obs"),
					 valueClass = "numeric")
setGeneric(name="get_deaths",
					 def=function(.Object) standardGeneric("get_deaths"),
					 valueClass = "numeric")
setGeneric(name="set_deaths",
					 def=function(.Object, id, times_of_deaths) standardGeneric("set_deaths"),
					 valueClass = "numeric")
setGeneric(name="get_sampled",
					 def=function(.Object) standardGeneric("get_sampled"),
					 valueClass = "logical")

setGeneric(name="get_PHI",
					 def=function(.Object) standardGeneric("get_PHI"),
					 valueClass = "matrix")
setGeneric(name="get_P",
					 def=function(.Object) standardGeneric("get_P"),
					 valueClass = "matrix")
setGeneric(name="set_PHI",
					 def=function(.Object, PHI) standardGeneric("set_PHI"),
					 valueClass = "matrix")
setGeneric(name="set_P",
					 def=function(.Object, P) standardGeneric("set_P"),
					 valueClass = "matrix")

setGeneric(name="get_ll_phi_components",
					 def=function(.Object, id) standardGeneric("get_ll_phi_components"),
					 valueClass = "numeric")
setGeneric(name="get_ll_p_components",
					 def=function(.Object, id) standardGeneric("get_ll_p_components"),
					 valueClass = "numeric")
setGeneric(name="get_log_posterior",
					 def=function(.Object) standardGeneric("get_log_posterior"),
					 valueClass = "numeric")
setGeneric(name="propose_deaths",
					 def=function(.Object) standardGeneric("propose_deaths"),
					 valueClass = "numeric")
setGeneric(name="get_last_pd",
					 def=function(.Object) standardGeneric("get_last_pd"),
					 valueClass = "numeric")
setGeneric(name="get_last_pd_vector",
					 def=function(.Object) standardGeneric("get_last_pd_vector"),
					 valueClass = "numeric")
setGeneric(name="get_pd",
					 def=function(.Object) standardGeneric("get_pd"),
					 valueClass = "numeric")
setGeneric(name="get_proposed_deaths",
					 def=function(.Object) standardGeneric("get_proposed_deaths"),
					 valueClass = "numeric")
